.TH CMONGUS 1 "Feb 2026" "cmongus 1.0" "User Commands"

.SH NAME
Cmongus \- displays a sus among us crewmate animation.

.SH SYNOPSIS
.B cmongus
.RI [ -C " color" ]

.SH DESCRIPTION
.B cmongus
displays an animated "Among Us" crewmate in the terminal.

.SH OPTIONS
.TP
.B -C color
Use this color for crewmate (default white).  Valid colors are green, red, blue, yellow, cyan, black, purple, white, pink, and grey.

.SH KEYSTROKES
The following keystrokes are available during execution:

.TP
.B 0-9
Adjust update speed

.SH EXAMPLES
cmongus

.SH AUTHOR
Jackson Lawrence
